on:
  repository_dispatch:
    types: [create-docker-image]

name: Docker Release

jobs:
  build:
    name: Create Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "HELLO WORLD"