on:
  workflow_dispatch:

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ELEVATED_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}-new-new
          release_name: Release ${{ github.ref }}-new-new
          body: |
            This is a test release 💩
          draft: false
          prerelease: false

      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     event-type: create-docker-image